services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME}
      CONFIG_URL: ${CONFIG_URL}
      APP_PROFILE: ${APP_PROFILE}
